#!/bin/bash

if (( $# != 1 )); then
	echo "Expected 1 argument"
	exit
fi

Path=$(realpath $1 2>/dev/null)
if [[ ! -f "$Path" ]]; then
	echo "File in argument didn't exist"
	exit
fi

if [[ ! -d ~/.trash ]]; then
	mkdir ~/.trash
fi

if [[ ! -f ~/.trash.log ]]; then
	> ~/.trash.log
fi

n=1
while [[ -f ~/.trash/$n ]]; do
	(( n++ ))
done

ln "$Path" ~/.trash/$n && rm "$Path" && echo "$Path : $n" >> ~/.trash.log && echo "$Path removed." || echo "File didn't remove"
